services:
  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www #
    ports:
      - "${APP_PORT:-80}:80"
    depends_on:
      - app
    networks:    # <--- TAMBAHKAN INI
      - backend  # <--- SUPAYA SATU JALUR DENGAN APP

  app:
    build:
      context: .
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      # Keep Composer packages off the Windows bind mount (much faster I/O on Docker Desktop).
      - laravel_vendor:/var/www/vendor
    depends_on:
      - db
      - redis
      - meilisearch
    networks:
      - backend

  # Ini Worker (Service B)
  worker:
    build: .
    container_name: laravel-worker
    # TAMBAHKAN/UBAH BARIS INI:
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    # command: php artisan RedisNotificationWorker  <-- COMMENT/HAPUS DULU BARIS INI
    tty: true  # <-- TAMBAHKAN INI biar container tetep hidup meskipun gak ada command
    restart: always
    volumes:
      - .:/var/www
      - laravel_vendor:/var/www/vendor
    depends_on:
      - app
      - redis
      - db
    networks: # <--- WAJIB TAMBAH INI
      - backend

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    # TAMBAHKAN COMMAND INI:
    command: ["mysqld", "--server-id=1", "--log-bin=mysql-bin"]
    environment:
      MYSQL_DATABASE: trello_test_aldo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: aldo
    volumes:
      - ./mysql-data:/var/lib/mysql # DIUBAH: Path Linux relatif
    networks:
      - backend

  mysql-slave:
    image: mysql:8.0
    container_name: laravel-db-slave
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: trello_test_aldo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: aldo
    command: ["mysqld", "--server-id=2", "--log-bin=mysql-bin", "--read-only=1"]
    volumes:
      - ./mysql-slave:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - backend

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: laravel-meili
    volumes:
      - ./meili-data:/meili_data
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  laravel_vendor:
