limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

server {
    listen 80;

    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;

    set $request_id_gen $request_id;
    add_header X-Request-ID $request_id_gen;

    # 1. HANDLE STATIC ASSETS (CSS, JS, SWAGGER UI)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|yaml|yml)$ {
        proxy_pass http://app:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. HANDLE API & ROUTES
    location / {
        limit_req zone=api_limit burst=10 nodelay;
        limit_req_status 429;

        proxy_pass http://app:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Request-ID $request_id_gen;
    }
}
