name: Deploy Laravel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Scripts
        run: |
          cd /var/www/laravel
          git reset --hard
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
